### ISSUE TITLE
Handle API errors with exceptions

### ISSUE THREAD

**Issue by maxkoryukov** [wronglink/mstranslator#16]
The translator returned string instead of an exception.

```
 t.translate('Hello, it is Duke', lang_from='en', lang_to='cn')
>> u"ArgumentOutOfRangeException: 'to' must be a valid language\r\nParameter name: to : ID=1230.V2_Json.Translate.2B006DE5"
```

**Comment by maxkoryukov** [comment]
And the problem not only in langcode (Chinese - `zh`, not `cn`), but in the returned value.

Now - text

Should be - exception

**Comment by wronglink** [comment]
@maxkoryukov thx for issue. I've added a API errors handling.
