### ISSUE TITLE
Thread-safe

### ISSUE THREAD

**Issue by maxkoryukov** [wronglink/mstranslator#17]
Please, provide a way, to make this API thread-safe..

This link could help: https://developers.google.com/api-client-library/python/guide/thread_safety

I am sure, the problem is in the `httplib2`

**Comment by maxkoryukov** [comment]
I thought, this project is dead;)

Since it is alive - I could send a PR for this issue;)

**Comment by wronglink** [comment]
@maxkoryukov I would be thankful for such PR!

**Comment by maxkoryukov** [comment]
Sorry... I have read the source code, and now I know, that `mstranslator` utilizes the `requests` lib. And _everybody_ knows: [requests is **thread-safe**](http://docs.python-requests.org/en/master/#supported-features)
