### ISSUE TITLE
Microsoft Translator Text APIs are moving to the Azure portal

### ISSUE THREAD

**Issue by cantero6** [wronglink/mstranslator#20]
Hi,

As Microsoft has announced, Microsoft Translator Text APIs are moving to the Azure portal.
Existing applications using Microsoft Translator need to be changed to continue working.

Here is the documentation / announcement about this change:
https://translatorbusiness.uservoice.com/knowledgebase/articles/1078534-microsoft-translator-on-azure?WT.mc_id=azurebg_email_Trans_1228_Microsoft_Translator_Azure_Portal

To begin using the Microsoft Translator subscription from Azure, you will need to replace the app authentication using your Microsoft Data Market Client ID and Client Secret with your new Azure key. The single Azure key is used to request an Azure token for the Microsoft Translator service.

Are you planning to update this library?

Thank you a lot!

**Comment by wronglink** [comment]
@cantero6 it's definitely worth to! Thanks for information.

**Comment by cantero6** [comment]
@wronglink thank you for your message. Great news :-)

When are you planning to change it?

Thank you a lot!!

**Comment by wronglink** [comment]
@cantero6 sorry, I'm a little bit lack of time for supporting this project right now. I'll try to do it ASAP, but can't give any promise.

**Comment by wronglink** [comment]
@cantero6 I've upgraded auth code, so now translator works with new **subscription key** from Azure portal.

**Comment by cantero6** [comment]
Thank you!

I will check it :-)

**Comment by fgmehlin** [comment]
Hi, I just created a subscription for this service, however it says that my key is invalid. Is there another issue with this ?
